/*
  Migracao Firebird 2.5 - Produto: PRECO_CUSTO, MARGEM_LUCRO, UND
  Executar uma vez no banco DBAVALIACAO antes de usar o cadastro atualizado.
  Idempotente: pode executar varias vezes sem falhar se colunas ja existirem.
*/

SET TERM ^ ;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_FIELDS
        WHERE RDB$RELATION_NAME = 'PRODUTO'
          AND RDB$FIELD_NAME = 'PRECO_CUSTO'
      )) THEN
    EXECUTE STATEMENT 'ALTER TABLE PRODUTO ADD PRECO_CUSTO NUMERIC(18,2) DEFAULT 0';
END
^

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_FIELDS
        WHERE RDB$RELATION_NAME = 'PRODUTO'
          AND RDB$FIELD_NAME = 'MARGEM_LUCRO'
      )) THEN
    EXECUTE STATEMENT 'ALTER TABLE PRODUTO ADD MARGEM_LUCRO NUMERIC(18,2) DEFAULT 0';
END
^

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
        SELECT 1
        FROM RDB$RELATION_FIELDS
        WHERE RDB$RELATION_NAME = 'PRODUTO'
          AND RDB$FIELD_NAME = 'UND'
      )) THEN
    EXECUTE STATEMENT 'ALTER TABLE PRODUTO ADD UND VARCHAR(6)';
END
^

SET TERM ; ^

UPDATE PRODUTO SET PRECO_CUSTO = 0 WHERE PRECO_CUSTO IS NULL;
UPDATE PRODUTO SET MARGEM_LUCRO = 0 WHERE MARGEM_LUCRO IS NULL;
UPDATE PRODUTO SET UND = '' WHERE UND IS NULL;

COMMIT;
